package com.abctreinamentos;
// Generated 29/07/2018 16:21:42 by Hibernate Tools 4.3.5.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long cpf;
	private String nome;
	private String email;

	public Cliente() {
	}

	public Cliente(long cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Override
	public String toString() {
		return "Cliente [ CPF=" + cpf + " Nome = " + nome + "Email = " + email + " ]";
	}
	
}
